/**
 * Everything the demo seed needs to know about the marketplace: cities, brands, their
 * owners and staff, categories and products, and the customers who shop there.
 * Plain data only; ./build.js turns it into database-ready documents.
 *
 * Product tuple keys:  n name | c category key | p price | cmp compare-at price | d description
 *                      a attributes | s stock now | low low-stock warning | st status
 *                      kw image keyword | track false = made to order
 */

const P = {
  productsAll: ['products.view', 'products.create', 'products.update', 'products.delete'],
  categoriesAll: ['categories.view', 'categories.create', 'categories.update', 'categories.delete'],
  orders: ['orders.view', 'orders.manage'],
  delivery: ['delivery.view', 'delivery.manage'],
  stock: ['inventory.view', 'inventory.manage'],
  viewOnly: ['products.view', 'categories.view', 'inventory.view', 'orders.view', 'delivery.view'],
}

const CITIES = [
  { key: 'faisalabad', name: 'Faisalabad', state: 'Punjab', country: 'Pakistan', isActive: true,
    description: 'The Manchester of Pakistan: a textile city of looms, dye houses and bustling cloth markets.' },
  { key: 'lahore', name: 'Lahore', state: 'Punjab', country: 'Pakistan', isActive: true,
    description: 'The cultural capital, known for its food, its old-city bazaars and its menswear and home-decor makers.' },
  { key: 'karachi', name: 'Karachi', state: 'Sindh', country: 'Pakistan', isActive: true,
    description: 'Pakistan\'s largest city and port, home to leather workshops, footwear makers and fast-moving trade.' },
  { key: 'islamabad', name: 'Islamabad', state: 'Islamabad Capital Territory', country: 'Pakistan', isActive: true,
    description: 'The planned capital, with a growing scene of independent jewellery and design studios.' },
  { key: 'multan', name: 'Multan', state: 'Punjab', country: 'Pakistan', isActive: true,
    description: 'The City of Saints, famous for blue pottery, handloom weaving and Multani sweets.' },
  { key: 'peshawar', name: 'Peshawar', state: 'Khyber Pakhtunkhwa', country: 'Pakistan', isActive: false,
    description: 'Coming soon: Peshawar is not open for orders yet.' },
]

const BRANDS = [
  // ───────────────────────────────────────────────────────── 1. Loom & Co.
  {
    key: 'loom', name: 'Loom & Co.', city: 'faisalabad', status: 'ACTIVE', ageDays: 170, skuPrefix: 'LOOM',
    description: 'Premium unstitched cloth woven and finished in Faisalabad. We make lawn, khaddar and chiffon in small batches, so every suit has a crisp print and a soft hand.',
    contact: { email: 'hello@loomandco.pk', phone: '+92 41 2617 480', whatsapp: '+92 300 7654321', website: 'https://loomandco.pk', instagram: '@loomandco.pk' },
    settings: { currency: 'PKR', freeDeliveryAbove: 5000, processingTime: '1 to 2 working days', returnWindowDays: 7 },
    owner: { name: 'Ayesha Rana', email: 'brand@citycart.local', phone: '+92 300 7654321', pw: 'brand' },
    store: {
      name: 'Loom & Co. Flagship', description: 'Our flagship showroom and dispatch point on Kachehri Bazaar, open six days a week.',
      address: { addressLine: 'Shop 22, Kachehri Bazaar, Clock Tower Chowk', city: 'Faisalabad', state: 'Punjab', country: 'Pakistan', postalCode: '38000' },
      contact: { phone: '+92 41 2617 480', email: 'store@loomandco.pk' }, hours: { open: '10:00', close: '20:00', closed: ['sun'] }, isActive: true,
    },
    staff: [
      { name: 'Usman Tariq', email: 'usman.tariq@citycart.demo', phone: '+92 321 6638120', jobTitle: 'Order Handler', permissions: [...P.orders, ...P.delivery] },
      { name: 'Fatima Noor', email: 'fatima.noor@citycart.demo', phone: '+92 333 6107754', jobTitle: 'Catalogue Manager', permissions: [...P.productsAll, ...P.categoriesAll, ...P.stock] },
    ],
    categories: [
      { key: 'women', name: 'Women\'s Unstitched', description: 'Three-piece and two-piece suits, cut and ready to stitch.' },
      { key: 'lawn', name: 'Lawn Collection', parent: 'women', description: 'Light combed-cotton lawn for the long Punjab summer.' },
      { key: 'khaddar', name: 'Winter Khaddar', parent: 'women', description: 'Brushed cotton khaddar that stays warm without feeling heavy.' },
      { key: 'eid', name: 'Eid Edit 2025', parent: 'women', description: 'Last year\'s festive collection. Kept for reference.', isActive: false },
      { key: 'men', name: 'Men\'s Fabric', description: 'Shalwar kameez and suiting cloth by the suit length.' },
      { key: 'dupattas', name: 'Dupattas & Shawls', description: 'Chiffon, voile and wool wraps to finish the outfit.' },
    ],
    products: [
      { n: 'Mehrunisa 3-Piece Printed Lawn', c: 'lawn', p: 4850, cmp: 5900, s: 42, low: 8, kw: 'lawn,fabric',
        d: 'Soft combed-cotton lawn with a hand-drawn paisley print on the shirt, plain dyed trousers and a matching voile dupatta. The colours are fast and the cloth is light enough for a Faisalabad July.',
        a: { fabric: 'Combed cotton lawn', pieces: 'Shirt 2.5 m, trouser 2.5 m, dupatta 2.5 m', color: 'Teal and ivory', care: 'Cold wash, iron on the reverse', origin: 'Faisalabad, Pakistan' } },
      { n: 'Gulbahar Embroidered Lawn 3-Piece', c: 'lawn', p: 6400, cmp: 7500, s: 27, low: 6, kw: 'embroidery,fabric',
        d: 'Front and sleeve embroidery in a rose and sage palette, on a lawn with a slight sheen. Comes with a printed back, plain trousers and a net-edged dupatta.',
        a: { fabric: 'Lawn with schiffli embroidery', pieces: 'Shirt 3 m, trouser 2.5 m, dupatta 2.5 m', color: 'Rose and sage', care: 'Dry clean recommended', origin: 'Faisalabad, Pakistan' } },
      { n: 'Sabz Bagh Digital Print Lawn', c: 'lawn', p: 3950, s: 64, low: 10, kw: 'floral,fabric',
        d: 'A garden of green leaves and small white blossoms, digitally printed so every petal stays sharp wash after wash. A good everyday suit.',
        a: { fabric: 'Cotton lawn', pieces: 'Shirt 2.5 m, trouser 2.5 m, dupatta 2.5 m', color: 'Green and white', care: 'Machine wash cold', origin: 'Faisalabad, Pakistan' } },
      { n: 'Noor Jahan Khaddar 3-Piece', c: 'khaddar', p: 5200, cmp: 6100, s: 31, low: 6, kw: 'winter,fabric',
        d: 'Brushed khaddar with a woven stripe, warm on cold mornings but breathable indoors. Includes a printed wool-blend shawl instead of a dupatta.',
        a: { fabric: 'Brushed cotton khaddar', pieces: 'Shirt 2.5 m, trouser 2.5 m, shawl 2.5 m', color: 'Mustard and charcoal', care: 'Wash cold, line dry', origin: 'Faisalabad, Pakistan' } },
      { n: 'Charkha Plain Khaddar Suit, Maroon', c: 'khaddar', p: 3400, s: 3, low: 5, kw: 'maroon,cloth',
        d: 'A plain dyed khaddar in a deep maroon that takes embroidery or lace beautifully. Sold as a two-piece suit length.',
        a: { fabric: 'Cotton khaddar', pieces: 'Shirt 2.5 m, trouser 2.5 m', color: 'Maroon', care: 'Wash cold', origin: 'Faisalabad, Pakistan' } },
      { n: 'Rawalpindi Wash & Wear Suiting, Charcoal', c: 'men', p: 3100, s: 55, low: 10, kw: 'suit,cloth',
        d: 'A dependable wash and wear blend for everyday shalwar kameez. Resists creasing, dries quickly and holds its colour.',
        a: { fabric: 'Polyester viscose blend', length: '4.5 m', color: 'Charcoal grey', care: 'Machine wash, no bleach', origin: 'Faisalabad, Pakistan' } },
      { n: 'Egyptian Cotton Kameez Cloth, Pure White', c: 'men', p: 3600, cmp: 4200, s: 38, low: 8, kw: 'white,cotton',
        d: 'A crisp white Egyptian-cotton blend with a fine weave that stays opaque and cool. The classic Eid and Friday cloth.',
        a: { fabric: 'Egyptian cotton blend', length: '4.5 m', color: 'White', care: 'Wash warm, iron hot', origin: 'Faisalabad, Pakistan' } },
      { n: 'Shabnam Chiffon Dupatta, Gold Border', c: 'dupattas', p: 2300, s: 0, low: 5, kw: 'chiffon,dupatta',
        d: 'A flowing pure chiffon dupatta with a hand-finished gold zari border. Pairs with plain suits for weddings and dawat evenings.',
        a: { fabric: 'Chiffon', length: '2.5 m', color: 'Blush pink', care: 'Dry clean only', origin: 'Faisalabad, Pakistan' } },
      { n: 'Camel Wool-Blend Winter Shawl', c: 'dupattas', p: 4400, cmp: 5200, s: 19, low: 5, kw: 'shawl,wool',
        d: 'A generous wool-blend shawl with a soft brushed finish. Light enough to carry, warm enough for a December evening.',
        a: { fabric: 'Wool-acrylic blend', size: '90 x 200 cm', color: 'Camel', care: 'Hand wash cold', origin: 'Faisalabad, Pakistan' } },
      { n: 'Kashmiri Embroidered Shawl', c: 'dupattas', p: 7800, s: 8, low: 3, st: 'DRAFT', kw: 'embroidered,shawl',
        d: 'Fine needle-work in the Kashmiri tradition across the border and corners. Still being photographed, so it is hidden for now.',
        a: { fabric: 'Wool', size: '100 x 200 cm', color: 'Ivory', care: 'Dry clean only', origin: 'Handmade in Punjab' } },
      { n: 'Plain Lawn Bundle (Last Season)', c: 'lawn', p: 1900, s: 0, st: 'ARCHIVED', kw: 'plain,lawn',
        d: 'A bundle of leftover plain lawn from last summer. Archived because the colours are no longer made.',
        a: { fabric: 'Cotton lawn', length: '8 m', color: 'Assorted pastels', care: 'Machine wash cold' } },
    ],
  },

  // ───────────────────────────────────────────────────────── 2. Rangrez Prints
  {
    key: 'rangrez', name: 'Rangrez Prints', city: 'faisalabad', status: 'ACTIVE', ageDays: 140, skuPrefix: 'RNG',
    description: 'Block-printed and digitally printed cloth sold by the metre. Our print house on Jaranwala Road runs wooden-block, screen and digital lines, and takes small custom jobs.',
    contact: { email: 'orders@rangrezprints.pk', phone: '+92 41 8723 119', whatsapp: '+92 301 4408821', website: 'https://rangrezprints.pk', instagram: '@rangrez.prints' },
    settings: { currency: 'PKR', freeDeliveryAbove: 8000, processingTime: '2 to 3 working days', returnWindowDays: 3 },
    owner: { name: 'Bilal Ahmed', email: 'bilal.ahmed@citycart.demo', phone: '+92 301 4408821', pw: 'demo' },
    store: {
      name: 'Rangrez Print House', description: 'A working print house. Walk-ins welcome to choose blocks and see the cloth being printed.',
      address: { addressLine: 'Plot 8, Jaranwala Road, Small Industrial Estate', city: 'Faisalabad', state: 'Punjab', country: 'Pakistan', postalCode: '38000' },
      contact: { phone: '+92 41 8723 119', email: 'house@rangrezprints.pk' }, hours: { open: '09:00', close: '18:00', closed: ['fri', 'sun'] }, isActive: true,
    },
    staff: [{ name: 'Zainab Yousaf', email: 'zainab.yousaf@citycart.demo', phone: '+92 302 9917345', jobTitle: 'Dispatch Packer', permissions: [...P.orders, ...P.delivery, 'inventory.view'] }],
    categories: [
      { key: 'block', name: 'Block Print Cloth', description: 'Hand-stamped with carved wooden blocks and natural-style dyes.' },
      { key: 'digital', name: 'Digital Print Cloth', description: 'Photographic detail and unlimited colours on cotton and lawn.' },
      { key: 'homeprint', name: 'Printed Home Pieces', description: 'Table runners, cushions and other small pieces made from our own cloth.' },
      { key: 'custom', name: 'Custom Printing', description: 'Swatch kits and bulk rolls for designers and boutiques.' },
    ],
    products: [
      { n: 'Ajrak Block Print Cotton, per metre', c: 'block', p: 650, cmp: 750, s: 240, low: 40, kw: 'ajrak,pattern',
        d: 'Traditional Sindhi ajrak in deep indigo and madder red, printed block by block and washed until it is soft. Priced per metre; order the length you need.',
        a: { fabric: 'Cotton', width: '44 inches', color: 'Indigo and red', technique: 'Wooden block print', sold: 'Per metre' } },
      { n: 'Indigo Bagh Print Cotton, per metre', c: 'block', p: 520, s: 180, low: 30, kw: 'indigo,block',
        d: 'A bagh (garden) pattern in two blues on natural cotton, inspired by Sanganer prints. Gets better with every wash.',
        a: { fabric: 'Cotton', width: '44 inches', color: 'Indigo on natural', technique: 'Wooden block print', sold: 'Per metre' } },
      { n: 'Mustard Dabu Print Cotton, per metre', c: 'block', p: 590, s: 95, low: 20, kw: 'mustard,print',
        d: 'Mud-resist dabu printing gives this mustard cloth its soft, cracked-ink texture. Each metre is a little different.',
        a: { fabric: 'Cotton', width: '44 inches', color: 'Mustard', technique: 'Dabu mud resist', sold: 'Per metre' } },
      { n: 'Floral Digital Lawn, per metre', c: 'digital', p: 480, s: 320, low: 50, kw: 'floral,print',
        d: 'A large-scale floral photographed from a Lahore garden, printed on soft lawn. Good for kameez, scarves and lining.',
        a: { fabric: 'Lawn', width: '52 inches', color: 'Multicolour floral', technique: 'Digital print', sold: 'Per metre' } },
      { n: 'Geometric Digital Cambric, per metre', c: 'digital', p: 430, s: 4, low: 25, kw: 'geometric,cloth',
        d: 'A sharp geometric repeat in navy and white on firm cambric. Holds pleats and stitches cleanly for shirts and cushions.',
        a: { fabric: 'Cambric', width: '52 inches', color: 'Navy and white', technique: 'Digital print', sold: 'Per metre' } },
      { n: 'Block-Print Table Runner', c: 'homeprint', p: 1650, cmp: 1950, s: 36, low: 6, kw: 'table,runner',
        d: 'A 180 cm table runner block printed in indigo with a hemmed edge. Wipe clean or wash cold.',
        a: { size: '35 x 180 cm', fabric: 'Cotton', color: 'Indigo', care: 'Wash cold' } },
      { n: 'Printed Cushion Cover Set of 2', c: 'homeprint', p: 1800, s: 48, low: 8, kw: 'cushion,print',
        d: 'Two 16 inch cushion covers in matching ajrak and bagh prints, with a concealed zip at the back.',
        a: { size: '16 x 16 inches', fabric: 'Cotton', pieces: '2', care: 'Machine wash cold' } },
      { n: 'Custom Print Swatch Kit (12 swatches)', c: 'custom', p: 1200, s: 0, low: 0, track: false, kw: 'swatches,fabric',
        d: 'Twelve 20 cm swatches of our best-selling blocks and digital prints so you can feel the cloth before ordering. Made to order, so there is no stock count.',
        a: { pieces: '12 swatches', size: '20 x 20 cm each', dispatch: 'Within 3 working days' } },
      { n: 'Bulk Ajrak Roll (20 m)', c: 'custom', p: 11500, cmp: 13000, s: 14, low: 3, kw: 'fabric,roll',
        d: 'A full 20 metre roll of ajrak block print cotton at a trade price, for boutiques and tailors.',
        a: { fabric: 'Cotton', length: '20 m', width: '44 inches', technique: 'Wooden block print' } },
    ],
  },

  // ───────────────────────────────────────────────────────── 3. Mehr Menswear
  {
    key: 'mehr', name: 'Mehr Menswear', city: 'lahore', status: 'ACTIVE', ageDays: 150, skuPrefix: 'MEHR',
    description: 'Stitched shalwar kameez, kurtas and waistcoats for men, cut to a clean modern fit by our tailors in Gulberg, Lahore.',
    contact: { email: 'care@mehrmenswear.pk', phone: '+92 42 3577 2210', whatsapp: '+92 322 8841207', website: 'https://mehrmenswear.pk', instagram: '@mehr.menswear' },
    settings: { currency: 'PKR', freeDeliveryAbove: 6000, processingTime: '1 working day', returnWindowDays: 7, sizeExchange: true },
    owner: { name: 'Hamza Sheikh', email: 'hamza.sheikh@citycart.demo', phone: '+92 322 8841207', pw: 'demo' },
    store: {
      name: 'Mehr Menswear Gulberg', description: 'Ready-to-wear and made-to-measure menswear. Alterations are free on the first purchase.',
      address: { addressLine: '47-B, MM Alam Road, Gulberg III', city: 'Lahore', state: 'Punjab', country: 'Pakistan', postalCode: '54660' },
      contact: { phone: '+92 42 3577 2210', email: 'gulberg@mehrmenswear.pk' }, hours: { open: '11:00', close: '22:00', closed: [] }, isActive: true,
    },
    staff: [{ name: 'Rafay Anwar', email: 'rafay.anwar@citycart.demo', phone: '+92 345 2210986', jobTitle: 'Sales Associate', permissions: P.viewOnly, isActive: false }],
    categories: [
      { key: 'sk', name: 'Shalwar Kameez', description: 'Stitched sets in cotton, wash and wear and blended fabrics.' },
      { key: 'kurta', name: 'Kurtas', description: 'Short and long kurtas, plain and embroidered.' },
      { key: 'waistcoat', name: 'Waistcoats & Coats', description: 'Layers for weddings and winter evenings.' },
    ],
    products: [
      { n: 'Classic White Cotton Shalwar Kameez', c: 'sk', p: 4200, cmp: 4900, s: 60, low: 10, kw: 'white,kurta',
        d: 'A clean, collared white shalwar kameez in breathable cotton, with ban collar option noted at checkout. Available S to XXL.',
        a: { fabric: 'Cotton', fit: 'Regular', sizes: 'S, M, L, XL, XXL', color: 'White', care: 'Machine wash warm' } },
      { n: 'Wash & Wear Shalwar Kameez, Slate Grey', c: 'sk', p: 3900, s: 45, low: 8, kw: 'grey,shalwar',
        d: 'Wash and wear that does not look like it. Stays sharp through a long day and needs almost no ironing.',
        a: { fabric: 'Poly-viscose', fit: 'Regular', sizes: 'S, M, L, XL', color: 'Slate grey', care: 'Machine wash, light iron' } },
      { n: 'Eid Embroidered Kurta, Sage Green', c: 'kurta', p: 5600, cmp: 6800, s: 22, low: 5, kw: 'green,kurta',
        d: 'Fine neckline and cuff embroidery on a soft cotton-silk blend. Cut slightly shorter for wearing over trousers.',
        a: { fabric: 'Cotton silk blend', fit: 'Slim', sizes: 'S, M, L, XL', color: 'Sage green', care: 'Hand wash cold' } },
      { n: 'Linen Kurta, Sand', c: 'kurta', p: 4800, s: 28, low: 6, kw: 'linen,kurta',
        d: 'A relaxed linen kurta with side slits and a soft collar. Wrinkles are part of the charm.',
        a: { fabric: 'Linen blend', fit: 'Relaxed', sizes: 'S, M, L, XL', color: 'Sand', care: 'Machine wash cold' } },
      { n: 'Black Velvet Waistcoat', c: 'waistcoat', p: 7200, cmp: 8500, s: 14, low: 4, kw: 'waistcoat,black',
        d: 'A fully lined black velvet waistcoat with a satin back and adjustable strap. Smart over a white kurta.',
        a: { fabric: 'Velvet with satin lining', fit: 'Tailored', sizes: 'S, M, L, XL', color: 'Black', care: 'Dry clean only' } },
      { n: 'Prince Coat Set, Navy', c: 'waistcoat', p: 18500, cmp: 21500, s: 6, low: 2, kw: 'suit,navy',
        d: 'A two-piece prince coat and trouser in navy wool-blend for weddings. Includes a free first alteration.',
        a: { fabric: 'Wool blend', fit: 'Tailored', sizes: '38 to 46 chest', color: 'Navy', care: 'Dry clean only' } },
      { n: 'Winter Wool Shawl for Men, Charcoal', c: 'waistcoat', p: 3900, s: 33, low: 6, kw: 'shawl,charcoal',
        d: 'A plain charcoal wool shawl, big enough to wrap twice. Pairs with shalwar kameez or a coat.',
        a: { fabric: 'Wool blend', size: '100 x 220 cm', color: 'Charcoal', care: 'Dry clean or hand wash cold' } },
      { n: 'Kids Kurta Pajama Set, Ivory', c: 'kurta', p: 2600, s: 40, low: 8, kw: 'kids,kurta',
        d: 'A soft ivory kurta pajama for boys aged 2 to 10, with an easy elastic waist for little ones.',
        a: { fabric: 'Cotton', fit: 'Regular', sizes: '2 to 10 years', color: 'Ivory', care: 'Machine wash warm' } },
    ],
  },

  // ───────────────────────────────────────────────────────── 4. Sukoon Home
  {
    key: 'sukoon', name: 'Sukoon Home', city: 'lahore', status: 'ACTIVE', ageDays: 120, skuPrefix: 'SKN',
    description: 'Calm, handmade pieces for the home: bedding, cushions, ceramics and woven decor from small workshops across Punjab.',
    contact: { email: 'hello@sukoonhome.pk', phone: '+92 42 3591 8830', whatsapp: '+92 333 5509142', website: 'https://sukoonhome.pk', instagram: '@sukoon.home' },
    settings: { currency: 'PKR', freeDeliveryAbove: 7000, processingTime: '2 working days', returnWindowDays: 7, giftWrap: true, taxRatePercent: 5 },
    owner: { name: 'Sana Mirza', email: 'sana.mirza@citycart.demo', phone: '+92 333 5509142', pw: 'demo' },
    store: {
      name: 'Sukoon Home Studio', description: 'A small studio and showroom in Model Town with the full range on display.',
      address: { addressLine: '12, Block C, Model Town Link Road', city: 'Lahore', state: 'Punjab', country: 'Pakistan', postalCode: '54700' },
      contact: { phone: '+92 42 3591 8830', email: 'studio@sukoonhome.pk' }, hours: { open: '10:00', close: '19:00', closed: ['sun'] }, isActive: true,
    },
    staff: [{ name: 'Maryam Javed', email: 'maryam.javed@citycart.demo', phone: '+92 300 4417762', jobTitle: 'Catalogue Assistant', permissions: ['products.view', 'products.create', 'products.update', 'categories.view', 'inventory.view', 'inventory.manage'] }],
    categories: [
      { key: 'bedding', name: 'Bedding', description: 'Sheets, quilts and bed covers in natural fabrics.' },
      { key: 'cushions', name: 'Cushions & Rugs', description: 'Cushion covers, throws and handwoven rugs.' },
      { key: 'kitchen', name: 'Kitchen & Dining', description: 'Handmade ceramics and table linen.' },
      { key: 'decor', name: 'Wall & Shelf Decor', description: 'Brass, terracotta and macrame for walls and shelves.' },
    ],
    products: [
      { n: 'Cotton Bedsheet Set, King, Sage Floral', c: 'bedding', p: 4900, cmp: 5800, s: 26, low: 5, kw: 'bedsheet,floral',
        d: 'A king-size bedsheet with two pillow covers in 220-thread-count cotton. Soft from the first night, and the sage floral print is gentle on the eyes.',
        a: { size: 'King (108 x 108 inches)', fabric: '220 TC cotton', pieces: '1 sheet, 2 pillow covers', color: 'Sage floral', care: 'Machine wash warm' } },
      { n: 'Quilted Bed Cover, Double, Ivory', c: 'bedding', p: 7200, cmp: 8400, s: 15, low: 4, kw: 'quilt,bed',
        d: 'A diamond-quilted cotton bed cover with a soft polyester fill. Works as a summer cover or an extra winter layer.',
        a: { size: 'Double (90 x 100 inches)', fabric: 'Cotton with polyester fill', color: 'Ivory', care: 'Machine wash gentle' } },
      { n: 'Block Print Cushion Cover, 16 x 16', c: 'cushions', p: 950, s: 85, low: 15, kw: 'cushion,cover',
        d: 'A single block-printed cushion cover in cotton with a hidden zip. Mix and match with others from the range.',
        a: { size: '16 x 16 inches', fabric: 'Cotton', color: 'Assorted', care: 'Machine wash cold' } },
      { n: 'Handwoven Jute Rug, 4 x 6 ft', c: 'cushions', p: 6800, s: 11, low: 3, kw: 'jute,rug',
        d: 'A natural jute rug woven by hand in Bahawalpur. Sturdy under a coffee table and kind to bare feet.',
        a: { size: '4 x 6 feet', material: 'Jute', color: 'Natural', care: 'Shake out, spot clean' } },
      { n: 'Hand-Painted Ceramic Mug Set of 4', c: 'kitchen', p: 2400, cmp: 2900, s: 30, low: 6, kw: 'ceramic,mug',
        d: 'Four stoneware mugs painted by hand with a different blue pattern each, from a studio in Multan.',
        a: { pieces: '4 mugs', capacity: '300 ml each', material: 'Stoneware', care: 'Dishwasher safe' } },
      { n: 'Embroidered Table Runner, Cream', c: 'kitchen', p: 2100, s: 24, low: 5, kw: 'table,linen',
        d: 'A cream cotton table runner with tonal embroidery along both ends. Dresses a plain table for dinner.',
        a: { size: '35 x 150 cm', fabric: 'Cotton', color: 'Cream', care: 'Wash cold' } },
      { n: 'Brass Diya Set of 3', c: 'decor', p: 1850, s: 52, low: 10, kw: 'brass,diya',
        d: 'Three hand-turned brass diyas in graduated sizes. Lovely on a shelf even when they are not lit.',
        a: { pieces: '3', material: 'Brass', size: '5, 7 and 9 cm', care: 'Polish with a soft cloth' } },
      { n: 'Macrame Wall Hanging', c: 'decor', p: 3200, cmp: 3900, s: 9, low: 3, kw: 'macrame,wall',
        d: 'A hand-knotted macrame hanging on a driftwood rod, in undyed cotton cord.',
        a: { size: '45 x 90 cm', material: 'Cotton cord and wood', color: 'Natural' } },
      { n: 'Terracotta Planter, Medium', c: 'decor', p: 1400, s: 70, low: 12, kw: 'terracotta,planter',
        d: 'A glazed-inside terracotta planter with a drainage hole and a saucer. Sized for a money plant or small fern.',
        a: { size: '8 inches', material: 'Terracotta', pieces: 'Pot and saucer' } },
    ],
  },

  // ───────────────────────────────────────────────────────── 5. Zaitoon Footwear
  {
    key: 'zaitoon', name: 'Zaitoon Footwear', city: 'karachi', status: 'ACTIVE', ageDays: 130, skuPrefix: 'ZTN',
    description: 'Handmade leather chappals, khussas and everyday shoes from our workshop in Korangi, Karachi. Real leather, stitched not glued.',
    contact: { email: 'sales@zaitoonfootwear.pk', phone: '+92 21 3511 6402', whatsapp: '+92 315 7720091', website: 'https://zaitoonfootwear.pk', instagram: '@zaitoon.footwear' },
    settings: { currency: 'PKR', freeDeliveryAbove: 5500, processingTime: '1 to 2 working days', returnWindowDays: 7, sizeExchange: true },
    owner: { name: 'Imran Qureshi', email: 'imran.qureshi@citycart.demo', phone: '+92 315 7720091', pw: 'demo' },
    store: {
      name: 'Zaitoon Workshop & Outlet', description: 'Factory outlet next to the workshop. Seconds and samples at lower prices.',
      address: { addressLine: 'Plot 31, Sector 6-A, Korangi Industrial Area', city: 'Karachi', state: 'Sindh', country: 'Pakistan', postalCode: '74900' },
      contact: { phone: '+92 21 3511 6402', email: 'outlet@zaitoonfootwear.pk' }, hours: { open: '10:00', close: '21:00', closed: [] }, isActive: true,
    },
    staff: [{ name: 'Danish Memon', email: 'danish.memon@citycart.demo', phone: '+92 312 4458803', jobTitle: 'Warehouse Lead', permissions: [...P.stock, ...P.orders, 'products.view', ...P.delivery] }],
    categories: [
      { key: 'chappal', name: 'Chappals & Sandals', description: 'Peshawari chappals, kolhapuris and open sandals.' },
      { key: 'khussa', name: 'Khussas', description: 'Traditional pointed and round-toe khussas.' },
      { key: 'sneakers', name: 'Sneakers & Loafers', description: 'Everyday closed shoes for work and weekends.' },
      { key: 'bags', name: 'Bags & Belts', description: 'Leather bags and belts made from offcuts of the same hides.' },
    ],
    products: [
      { n: 'Peshawari Chappal, Tan Leather', c: 'chappal', p: 4500, cmp: 5200, s: 38, low: 6, kw: 'sandals,leather',
        d: 'A hand-stitched Peshawari chappal in vegetable-tanned leather with a sturdy tyre-tread sole. Stiff for a week, then it moulds to your foot.',
        a: { material: 'Vegetable-tanned leather', sole: 'Rubber tread', sizes: 'UK 6 to 12', color: 'Tan', care: 'Brush clean, leather balm monthly' } },
      { n: 'Kolhapuri Sandals, Women\'s', c: 'chappal', p: 3200, s: 29, low: 6, kw: 'kolhapuri,sandals',
        d: 'Flat kolhapuri sandals with a braided toe loop, light enough to walk in all day.',
        a: { material: 'Leather', sole: 'Leather', sizes: 'EU 36 to 41', color: 'Brown', care: 'Wipe with a dry cloth' } },
      { n: 'Hand-Embroidered Khussa, Gold', c: 'khussa', p: 3800, cmp: 4600, s: 17, low: 4, kw: 'khussa,gold',
        d: 'A women\'s khussa with gold zari embroidery across the toe and a cushioned insole. Made for mehndi nights.',
        a: { material: 'Leather and zari thread', sole: 'Leather', sizes: 'EU 36 to 41', color: 'Gold', care: 'Keep dry, wipe clean' } },
      { n: 'Men\'s Khussa, Black Round Toe', c: 'khussa', p: 3600, s: 21, low: 5, kw: 'khussa,black',
        d: 'A classic black round-toe khussa with a flexible sole. Goes with shalwar kameez and waistcoats.',
        a: { material: 'Leather', sole: 'Rubber', sizes: 'UK 6 to 12', color: 'Black', care: 'Polish with black cream' } },
      { n: 'Canvas Sneakers, White', c: 'sneakers', p: 3400, cmp: 3900, s: 54, low: 10, kw: 'sneakers,white',
        d: 'Simple white canvas sneakers with a vulcanised sole. Easy to clean and goes with everything.',
        a: { material: 'Canvas', sole: 'Rubber', sizes: 'EU 38 to 45', color: 'White', care: 'Hand wash with mild soap' } },
      { n: 'Leather Loafers, Brown', c: 'sneakers', p: 6900, cmp: 8200, s: 12, low: 3, kw: 'loafers,brown',
        d: 'Brown leather loafers with a padded collar. Smart enough for the office, comfortable enough for a long day.',
        a: { material: 'Full-grain leather', sole: 'Leather with rubber heel', sizes: 'UK 6 to 11', color: 'Brown', care: 'Shoe tree and polish' } },
      { n: 'Women\'s Leather Tote Bag, Tan', c: 'bags', p: 7800, s: 2, low: 4, kw: 'tote,bag',
        d: 'A roomy tote with a zipped inner pocket and a laptop sleeve that fits a 14 inch machine.',
        a: { material: 'Leather', size: '38 x 30 x 12 cm', color: 'Tan', care: 'Wipe clean, avoid water' } },
      { n: 'Laptop Messenger Bag, Dark Brown', c: 'bags', p: 6400, cmp: 7400, s: 18, low: 4, kw: 'messenger,bag',
        d: 'A slim messenger bag with a padded laptop compartment, two outer pockets and an adjustable strap.',
        a: { material: 'Leather and cotton lining', size: '40 x 30 x 8 cm', color: 'Dark brown', care: 'Leather conditioner every few months' } },
      { n: 'Men\'s Leather Belt, Black', c: 'bags', p: 1800, s: 66, low: 10, kw: 'belt,leather',
        d: 'A 35 mm full-grain leather belt with a brushed steel buckle. Available in 30 to 42 inch waist sizes.',
        a: { material: 'Full-grain leather', width: '35 mm', sizes: '30 to 42 inch', color: 'Black' } },
    ],
  },

  // ───────────────────────────────────────────────────────── 6. Naqsh Jewellery
  {
    key: 'naqsh', name: 'Naqsh Jewellery', city: 'islamabad', status: 'ACTIVE', ageDays: 100, skuPrefix: 'NQS',
    description: 'Artificial jewellery that looks like heirlooms: kundan, meenakari and oxidised silver pieces designed in our F-7 studio.',
    contact: { email: 'studio@naqshjewellery.pk', phone: '+92 51 2655 981', whatsapp: '+92 332 6014488', website: 'https://naqshjewellery.pk', instagram: '@naqsh.jewellery' },
    settings: { currency: 'PKR', freeDeliveryAbove: 4000, processingTime: '1 to 2 working days', returnWindowDays: 5, giftWrap: true },
    owner: { name: 'Hira Aslam', email: 'hira.aslam@citycart.demo', phone: '+92 332 6014488', pw: 'demo' },
    store: {
      name: 'Naqsh Studio F-7', description: 'Appointment-friendly studio with a bridal corner and a repair desk.',
      address: { addressLine: 'Shop 9, Jinnah Super Market, F-7 Markaz', city: 'Islamabad', state: 'Islamabad Capital Territory', country: 'Pakistan', postalCode: '44000' },
      contact: { phone: '+92 51 2655 981', email: 'f7@naqshjewellery.pk' }, hours: { open: '12:00', close: '21:00', closed: ['mon'] }, isActive: true,
    },
    staff: [{ name: 'Komal Shahid', email: 'komal.shahid@citycart.demo', phone: '+92 301 8832006', jobTitle: 'Studio Manager', permissions: [...P.productsAll, ...P.categoriesAll, ...P.stock, ...P.orders, ...P.delivery, 'employees.view'] }],
    categories: [
      { key: 'earrings', name: 'Earrings', description: 'Jhumkas, studs and statement drops.' },
      { key: 'necklaces', name: 'Necklaces & Sets', description: 'Chokers, long haar and full bridal sets.' },
      { key: 'bangles', name: 'Bangles & Rings', description: 'Stacks of bangles, cuffs and cocktail rings.' },
    ],
    products: [
      { n: 'Kundan Jhumka Earrings, Emerald', c: 'earrings', p: 2800, cmp: 3400, s: 34, low: 6, kw: 'jhumka,earrings',
        d: 'Gold-plated jhumkas set with kundan stones and an emerald-green bead drop. Lightweight and push-back secure.',
        a: { material: 'Brass, gold plating, kundan', length: '6 cm', color: 'Gold and emerald', care: 'Keep dry, store in the pouch' } },
      { n: 'Oxidised Silver Jhumkay', c: 'earrings', p: 1600, s: 58, low: 10, kw: 'silver,earrings',
        d: 'Antique-finish oxidised jhumkay with small ghungroo that chime when you move. A summer favourite with lawn suits.',
        a: { material: 'Oxidised alloy', length: '5 cm', color: 'Antique silver', care: 'Wipe with a soft cloth' } },
      { n: 'Pearl Choker Necklace', c: 'necklaces', p: 3900, cmp: 4700, s: 19, low: 4, kw: 'pearl,necklace',
        d: 'Three strands of freshwater-style pearls on a gold-plated clasp. Sits neatly at the collarbone.',
        a: { material: 'Glass pearls, gold plating', length: '16 inch plus extender', color: 'Ivory and gold', care: 'Avoid perfume and water' } },
      { n: 'Meenakari Pendant on Long Chain', c: 'necklaces', p: 2400, s: 25, low: 5, kw: 'pendant,necklace',
        d: 'A peacock-motif pendant painted in meenakari enamel on a 28 inch chain. Pairs well with plain kameez.',
        a: { material: 'Brass, enamel', length: '28 inch', color: 'Blue and green', care: 'Keep dry' } },
      { n: 'Bridal Set: Kundan Necklace & Earrings', c: 'necklaces', p: 18500, cmp: 22000, s: 5, low: 2, kw: 'bridal,jewellery',
        d: 'A full bridal set: a layered kundan necklace, matching earrings and a tikka. Comes in a lined presentation box.',
        a: { material: 'Brass, gold plating, kundan', pieces: 'Necklace, earrings, tikka', color: 'Gold and ruby red', care: 'Store in the box' } },
      { n: 'Gold-Plated Bangles, Set of 4', c: 'bangles', p: 3200, s: 40, low: 8, kw: 'gold,bangles',
        d: 'Four slim gold-plated bangles with a fine hammered finish. Wear them together or one at a time.',
        a: { material: 'Brass, gold plating', size: '2.4, 2.6 and 2.8 available', pieces: '4', color: 'Gold', care: 'Keep dry' } },
      { n: 'Adjustable Cocktail Ring, Rose Quartz', c: 'bangles', p: 1250, s: 44, low: 8, kw: 'ring,quartz',
        d: 'A bold ring with a rose-quartz coloured stone in a scalloped setting. The band adjusts to most sizes.',
        a: { material: 'Alloy, glass stone', size: 'Adjustable', color: 'Rose and gold', care: 'Keep dry' } },
    ],
  },

  // ───────────────────────────────────────────────────────── 7. Chenab Handlooms (PENDING)
  {
    key: 'chenab', name: 'Chenab Handlooms', city: 'multan', status: 'PENDING', ageDays: 3, skuPrefix: 'CHN',
    description: 'Handloom khes and Multani blue pottery from family workshops in Multan. New on CityCart and waiting for approval.',
    contact: { email: 'chenabhandlooms@gmail.com', phone: '+92 61 4512 077', whatsapp: '+92 306 1193420' },
    settings: { currency: 'PKR', processingTime: '3 to 5 working days' },
    owner: { name: 'Rukhsana Bibi', email: 'rukhsana.bibi@citycart.demo', phone: '+92 306 1193420', pw: 'demo' },
    store: {
      name: 'Chenab Handloom House', description: 'A family workshop with a small shop front on Hussain Agahi Road.',
      address: { addressLine: 'Shop 3, Hussain Agahi Road', city: 'Multan', state: 'Punjab', country: 'Pakistan', postalCode: '60000' },
      contact: { phone: '+92 61 4512 077', email: 'chenabhandlooms@gmail.com' }, hours: { open: '09:30', close: '19:30', closed: ['fri'] }, isActive: true,
    },
    staff: [],
    categories: [{ key: 'khes', name: 'Khes & Pottery', description: 'Handloom khes blankets and blue pottery.' }],
    products: [
      { n: 'Handloom Khes, Double Bed', c: 'khes', p: 3800, s: 12, low: 3, st: 'DRAFT', kw: 'khes,handloom',
        d: 'A double-bed cotton khes woven on a pit loom in checks of indigo and cream. Drafted while the brand is reviewed.',
        a: { size: '90 x 100 inches', fabric: 'Cotton', color: 'Indigo and cream' } },
      { n: 'Multani Blue Pottery Vase', c: 'khes', p: 2900, s: 8, low: 2, st: 'DRAFT', kw: 'pottery,vase',
        d: 'A hand-thrown vase glazed in cobalt blue with a traditional floral border. Waiting for approval.',
        a: { height: '28 cm', material: 'Glazed ceramic', color: 'Cobalt blue' } },
    ],
  },

  // ───────────────────────────────────────────────────────── 8. Gulberg Gadgets (SUSPENDED)
  {
    key: 'gadgets', name: 'Gulberg Gadgets', city: 'lahore', status: 'SUSPENDED', ageDays: 90, skuPrefix: 'GGD',
    description: 'Phone accessories and small gadgets. Temporarily suspended while a customer complaint is investigated.',
    contact: { email: 'support@gulberggadgets.pk', phone: '+92 42 3588 1190', whatsapp: '+92 324 5578160' },
    settings: { currency: 'PKR', freeDeliveryAbove: 3000, processingTime: '1 working day' },
    owner: { name: 'Taimoor Butt', email: 'taimoor.butt@citycart.demo', phone: '+92 324 5578160', pw: 'demo' },
    store: {
      name: 'Gulberg Gadgets Outlet', description: 'Phone cases, chargers and small electronics.',
      address: { addressLine: '15, Hafeez Centre, Main Boulevard Gulberg', city: 'Lahore', state: 'Punjab', country: 'Pakistan', postalCode: '54660' },
      contact: { phone: '+92 42 3588 1190', email: 'outlet@gulberggadgets.pk' }, hours: { open: '11:00', close: '21:00', closed: [] }, isActive: true,
    },
    staff: [],
    categories: [{ key: 'acc', name: 'Phone Accessories', description: 'Cases, chargers and cables.' }],
    products: [
      { n: 'Braided USB-C Cable, 2 m', c: 'acc', p: 950, s: 120, low: 20, kw: 'cable,usb',
        d: 'A 2 metre braided USB-C fast-charge cable with reinforced ends. Tested to 60 W.',
        a: { length: '2 m', connector: 'USB-C to USB-C', power: 'Up to 60 W', color: 'Black' } },
      { n: 'Shockproof Phone Case, Clear', c: 'acc', p: 1200, s: 75, low: 15, kw: 'phone,case',
        d: 'A clear shockproof case with raised edges to protect the screen and camera.',
        a: { material: 'TPU and polycarbonate', color: 'Clear', compatibility: 'Several popular models; choose at checkout' } },
    ],
  },

  // ───────────────────────────────────────────────────────── 9. Quick Cart Deals (TERMINATED)
  {
    key: 'quick', name: 'Quick Cart Deals', city: 'karachi', status: 'TERMINATED', ageDays: 80, skuPrefix: 'QCD',
    terminationReason: 'Repeated reports of items not matching their listings, and orders accepted but never shipped.',
    terminatedDaysAgo: 2, graceHours: 168,
    description: 'Discount household and fashion items. Terminated by CityCart for breaking the seller rules.',
    contact: { email: 'quickcartdeals@gmail.com', phone: '+92 21 3499 7712', whatsapp: '+92 333 1109004' },
    settings: { currency: 'PKR', processingTime: '2 working days' },
    owner: { name: 'Faraz Siddiqui', email: 'faraz.siddiqui@citycart.demo', phone: '+92 333 1109004', pw: 'demo' },
    store: {
      name: 'Quick Cart Warehouse', description: 'Closed.',
      address: { addressLine: 'Warehouse 4, SITE Area, Mauripur Road', city: 'Karachi', state: 'Sindh', country: 'Pakistan', postalCode: '75700' },
      contact: { phone: '+92 21 3499 7712', email: 'quickcartdeals@gmail.com' }, hours: { open: '10:00', close: '18:00', closed: ['sun'] }, isActive: false,
    },
    staff: [{ name: 'Adeel Raza', email: 'adeel.raza@citycart.demo', phone: '+92 340 2285917', jobTitle: 'Packer', permissions: [...P.orders, ...P.delivery] }],
    categories: [{ key: 'misc', name: 'Fashion & Household', description: 'Assorted discount goods.' }],
    products: [
      { n: 'Ladies Handbag Combo (3 pcs)', c: 'misc', p: 2200, s: 40, low: 5, st: 'INACTIVE', kw: 'handbag,combo',
        d: 'A three-piece handbag combo. Listing disabled after the brand was terminated.',
        a: { pieces: '3', material: 'Synthetic leather' } },
      { n: 'Stainless Steel Lunch Box', c: 'misc', p: 1400, s: 25, low: 5, st: 'INACTIVE', kw: 'lunch,box',
        d: 'A two-tier stainless steel lunch box. Listing disabled after the brand was terminated.',
        a: { material: 'Stainless steel', capacity: '900 ml' } },
    ],
  },

  // ───────────────────────────────────────────────────────── 10. Silk Route Imports (REJECTED)
  {
    key: 'silkroute', name: 'Silk Route Imports', city: 'islamabad', status: 'REJECTED', ageDays: 20, skuPrefix: 'SRI',
    description: 'Imported silks and scarves. Application rejected: the supplier documents could not be verified.',
    contact: { email: 'silkrouteimports@outlook.com', phone: '+92 51 2290 645' },
    settings: { currency: 'PKR' },
    owner: { name: 'Nadia Farooq', email: 'nadia.farooq@citycart.demo', phone: '+92 336 7745519', pw: 'demo' },
    store: {
      name: 'Silk Route Showroom', description: 'Application rejected.',
      address: { addressLine: 'Office 12, Blue Area, Jinnah Avenue', city: 'Islamabad', state: 'Islamabad Capital Territory', country: 'Pakistan', postalCode: '44000' },
      contact: { phone: '+92 51 2290 645', email: 'silkrouteimports@outlook.com' }, hours: { open: '10:00', close: '17:00', closed: ['sat', 'sun'] }, isActive: false,
    },
    staff: [],
    categories: [{ key: 'silk', name: 'Silks & Scarves', description: 'Imported silks.' }],
    products: [
      { n: 'Mulberry Silk Scarf, Midnight', c: 'silk', p: 5400, s: 10, low: 2, st: 'DRAFT', kw: 'silk,scarf',
        d: 'A mulberry silk scarf in midnight blue with a hand-rolled hem. Never published.',
        a: { fabric: 'Mulberry silk', size: '90 x 90 cm', color: 'Midnight blue' } },
    ],
  },
]

const CUSTOMERS = [
  { name: 'Sana Iqbal', email: 'sana.iqbal@citycart.demo', phone: '+92 300 1182047', city: 'Faisalabad', state: 'Punjab', address: 'House 41, Street 5, Peoples Colony No. 1', postalCode: '38000', note: 'Please call before arriving.' },
  { name: 'Ali Raza', email: 'ali.raza@citycart.demo', phone: '+92 321 4476098', city: 'Lahore', state: 'Punjab', address: 'House 18-A, Block F, Johar Town', postalCode: '54782' },
  { name: 'Mahnoor Tariq', email: 'mahnoor.tariq@citycart.demo', phone: '+92 333 9005512', city: 'Karachi', state: 'Sindh', address: 'Flat 203, Saima Pearl, Block 13-D, Gulshan-e-Iqbal', postalCode: '75300', note: 'Leave with the guard if no one answers.' },
  { name: 'Hassan Mehmood', email: 'hassan.mehmood@citycart.demo', phone: '+92 345 7702831', city: 'Islamabad', state: 'Islamabad Capital Territory', address: 'House 7, Street 22, F-10/3', postalCode: '44000' },
  { name: 'Zoya Khan', email: 'zoya.khan@citycart.demo', phone: '+92 302 5589410', city: 'Lahore', state: 'Punjab', address: '27 Askari 10, Sarfraz Rafiqui Road', postalCode: '54810', note: 'Gate code 4471.' },
  { name: 'Faisal Chaudhry', email: 'faisal.chaudhry@citycart.demo', phone: '+92 311 3347760', city: 'Faisalabad', state: 'Punjab', address: 'Plot 112, Canal Road, near Satiana Road', postalCode: '38000' },
  { name: 'Areeba Siddiqui', email: 'areeba.siddiqui@citycart.demo', phone: '+92 334 2268091', city: 'Karachi', state: 'Sindh', address: 'House 56, Phase 5, DHA', postalCode: '75500' },
  { name: 'Waqar Ahmed', email: 'waqar.ahmed@citycart.demo', phone: '+92 301 6619248', city: 'Multan', state: 'Punjab', address: 'House 9, Street 3, Shah Rukn-e-Alam Colony', postalCode: '60000' },
  { name: 'Hina Malik', email: 'hina.malik@citycart.demo', phone: '+92 322 0874416', city: 'Islamabad', state: 'Islamabad Capital Territory', address: 'Apartment 5B, Silver Oaks, F-10 Markaz', postalCode: '44000', note: 'Call on arrival.' },
  { name: 'Umar Farooq', email: 'umar.farooq@citycart.demo', phone: '+92 315 9983027', city: 'Lahore', state: 'Punjab', address: 'House 301, Street 14, Wapda Town Phase 1', postalCode: '54770' },
  { name: 'Iqra Nadeem', email: 'iqra.nadeem@citycart.demo', phone: '+92 303 4410582', city: 'Faisalabad', state: 'Punjab', address: 'House 66, Street 9, Gulistan Colony', postalCode: '38000' },
  { name: 'Shahzaib Ali', email: 'shahzaib.ali@citycart.demo', phone: '+92 336 1127745', city: 'Karachi', state: 'Sindh', address: 'B-24, Block 2, Nazimabad', postalCode: '74600' },
  { name: 'Laiba Rehman', email: 'laiba.rehman@citycart.demo', phone: '+92 340 6671390', city: 'Lahore', state: 'Punjab', address: 'House 5, Lane 3, Cavalry Ground', postalCode: '54800' },
  { name: 'Dawood Hussain', email: 'dawood.hussain@citycart.demo', phone: '+92 344 8825163', city: 'Multan', state: 'Punjab', address: 'House 23, Block B, Gulgasht Colony', postalCode: '60000', inactive: true },
]

const ADMIN = { name: 'Super Admin', email: 'admin@citycart.local', phone: '+92 300 0000001' }

// Carts that are currently open (customer index -> [brand key, product name, quantity][])
const CARTS = [
  [0, [['loom', 'Mehrunisa 3-Piece Printed Lawn', 2], ['loom', 'Camel Wool-Blend Winter Shawl', 1]]],
  [3, [['naqsh', 'Pearl Choker Necklace', 1], ['naqsh', 'Oxidised Silver Jhumkay', 2]]],
  [6, [['zaitoon', 'Canvas Sneakers, White', 1]]],
  [9, [['mehr', 'Black Velvet Waistcoat', 1], ['sukoon', 'Block Print Cushion Cover, 16 x 16', 4]]],
  [11, [['rangrez', 'Ajrak Block Print Cotton, per metre', 6]]],
]

// Words reviewers use, by brand: what they praise, and what they grumble about.
const REMARKS = {
  loom: {
    good: ['The lawn is soft and the print stayed sharp after the first wash.', 'The cloth is a generous length and the dupatta matches perfectly.', 'The colours are exactly like the photos, which almost never happens online.', 'It stitched beautifully and I got three compliments at the first wedding.'],
    bad: ['The shade was a little lighter than the photo.', 'The dupatta was shorter than I expected.', 'It arrived with a faint smell that took two washes to go.'],
  },
  rangrez: {
    good: ['The block print is crisp and the indigo has real depth.', 'I ordered a lot and the pattern was consistent across the whole length.', 'It softened nicely after washing and did not bleed.', 'Perfect for the cushions I was making for my shop.'],
    bad: ['Each metre looks a little different, which is expected, but I wanted a closer match.', 'The edge was uneven on one cut.', 'Shrank more than I allowed for, so wash it before cutting.'],
  },
  mehr: {
    good: ['The fit is clean and the stitching is neat all round.', 'The fabric breathes well and held up through a long wedding day.', 'The size chart was accurate, so no exchange was needed.', 'Looks far more expensive than the price.'],
    bad: ['The sleeves were slightly long for me.', 'A loose thread near the hem, easily fixed.', 'The shade was a touch darker than pictured.'],
  },
  sukoon: {
    good: ['It makes the bedroom feel calmer. The cotton is soft and the print is gentle.', 'Beautifully packed and the quality is clearly handmade.', 'It looks even better in the room than in the photos.', 'Washed twice and nothing faded.'],
    bad: ['One cushion seam was a little loose.', 'A bit smaller than I imagined from the photos.', 'Took a day longer than promised, but the item itself is lovely.'],
  },
  zaitoon: {
    good: ['Real leather you can smell and feel. The stitching is solid.', 'Stiff for a few days and then it moulded to my feet.', 'The sizing is true and the sole feels durable.', 'Comfortable straight away, which I did not expect from a khussa.'],
    bad: ['Needed a week of breaking in.', 'I had to exchange for a half size up, which they handled quickly.', 'The colour is a little brighter than the photos.'],
  },
  naqsh: {
    good: ['They look like real heirloom pieces, and they are surprisingly light to wear.', 'The finish is lovely and nothing felt cheap.', 'Packed like a gift, and the gold tone is warm rather than brassy.', 'Wore them all evening and got asked where they were from.'],
    bad: ['The clasp was a little stiff.', 'One stone looked slightly off-centre.', 'Smaller than I imagined from the photos.'],
  },
  quick: { good: ['It arrived as described.'], bad: ['Not as pictured.', 'The quality was poor for the price.'] },
}

module.exports = { P, CITIES, BRANDS, CUSTOMERS, ADMIN, CARTS, REMARKS }